# This workflow runs Lighthouse PWA certification test against a new deployment of the ambianic web site
name: Lighthouse PWA Certification CI

on: deployment_status

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Lighthouse PWA check against github pages deployment
      uses: treosh/lighthouse-ci-action@v2
      with:
        urls: |
          ${{ github.event.deployment_status.target_url }}
        uploadArtifacts: false # save results as an action artifacts
        temporaryPublicStorage: false # upload lighthouse report to the temporary storage
        configPath: '.github/workflows/lighthouserc.json' # PWA checks
